[package]
name = "voxel_tool"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gdnative = "0.9.3"
<<<<<<< HEAD
ndarray = "0.15.1"
=======
rand = "0.3"
>>>>>>> 629216dbc2a993b1f5e2d47ea65217d330d7c9d7

[lib]
crate-type = ["cdylib"]
