[package]
name = "voxel_tool"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gdnative = "0.9.3"
rand = "0.3"

[lib]
crate-type = ["cdylib"]
